
    const KEY='tuckstock-v1-state';
    const demoProducts=[
      {id:'p1',name:'Amagwinya',type:'prepared',category:'Food',price:5,cost:2,qty:18,low:5,barcode:'',emoji:'🥯'},
      {id:'p2',name:'Loose Sweets',type:'loose',category:'Sweets',price:1,cost:.5,qty:100,low:20,barcode:'',emoji:'🍬'},
      {id:'p3',name:'Cigarettes',type:'loose',category:'Tobacco',price:3,cost:2,qty:20,low:5,barcode:'',emoji:'◻️'},
      {id:'p4',name:'Bread',type:'packaged',category:'Grocery',price:18,cost:14,qty:12,low:3,barcode:'6001007003765',emoji:'🍞'},
      {id:'p5',name:'Energy Drink',type:'packaged',category:'Drinks',price:15,cost:10,qty:24,low:6,barcode:'6009801167227',emoji:'⚡'}
    ];
    const demoState=()=>({products:structuredClone(demoProducts),sales:[],movements:[],basket:{},counts:[],createdAt:Date.now()});
    let state=load(); let saleFilter='all'; let scanTarget='sale'; let scanStream=null; let scanTimer=null;
    function load(){try{return JSON.parse(localStorage.getItem(KEY))||demoState()}catch{return demoState()}}
    function save(){localStorage.setItem(KEY,JSON.stringify(state));renderAll()}
    function money(n){return new Intl.NumberFormat('en-ZA',{style:'currency',currency:'ZAR',maximumFractionDigits:2}).format(Number(n)||0)}
    function todayKey(){const d=new Date(); return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')}
    function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
    function go(id){document.querySelectorAll('.screen').forEach(s=>s.classList.toggle('active',s.id===id));document.querySelectorAll('[data-go]').forEach(b=>b.classList.toggle('active',b.dataset.go===id&&b.closest('.nav')));window.scrollTo({top:0,behavior:'smooth'});renderAll()}
    document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.go)));
    document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>closeSheet(b.dataset.close)));
    function openSheet(id){document.getElementById(id).classList.add('open')}
    function closeSheet(id){document.getElementById(id).classList.remove('open'); if(id==='scanSheet') stopScanner()}
    document.querySelectorAll('.sheet').forEach(s=>s.addEventListener('click',e=>{if(e.target===s)closeSheet(s.id)}));

    function renderHome(){
      const tk=todayKey(); const sales=state.sales.filter(s=>s.day===tk); const total=sales.reduce((a,s)=>a+s.total,0); const units=sales.reduce((a,s)=>a+s.items.reduce((x,i)=>x+i.qty,0),0); const low=state.products.filter(p=>p.qty<=p.low);
      todaySales.textContent=money(total); unitsSold.textContent=units; lowCount.textContent=low.length; lowSubtitle.textContent=low.length?`${low.length} need attention`:'All good';
      lowStockList.innerHTML=low.length?low.map(p=>`<div class="row"><div class="meta"><div class="name">${esc(p.name)}</div><div class="sub">Reorder at ${p.low}</div></div><div class="qty low">${p.qty} left</div></div>`).join(''):'<div class="empty">No products are below their low-stock level.</div>';
    }
    function renderSaleProducts(){const q=saleSearch.value.trim().toLowerCase();const ps=state.products.filter(p=>(saleFilter==='all'||p.type===saleFilter||(saleFilter==='loose'&&p.type==='prepared'))&&p.name.toLowerCase().includes(q));saleProducts.innerHTML=ps.length?ps.map(p=>`<button class="product-card" data-add="${p.id}" ${p.qty<=0?'disabled':''}><span class="emoji">${p.emoji||'📦'}</span><b>${esc(p.name)}</b><div class="price">${money(p.price)}</div><div class="stock ${p.qty<=p.low?'low':''}">${p.qty} left</div></button>`).join(''):'<div class="empty" style="grid-column:1/-1">No matching products.</div>';document.querySelectorAll('[data-add]').forEach(b=>b.addEventListener('click',()=>addToBasket(b.dataset.add,1)))}
    function addToBasket(id,n){const p=state.products.find(x=>x.id===id); if(!p||p.qty<=0)return; const cur=state.basket[id]||0; state.basket[id]=Math.min(p.qty,cur+n); saveBasketOnly();toast(`${p.name} added`)}
    function saveBasketOnly(){localStorage.setItem(KEY,JSON.stringify(state));renderBasket();renderSaleProducts()}
    function basketEntries(){return Object.entries(state.basket).map(([id,qty])=>({p:state.products.find(x=>x.id===id),qty})).filter(x=>x.p&&x.qty>0)}
    function renderBasket(){const es=basketEntries();const count=es.reduce((a,x)=>a+x.qty,0);const total=es.reduce((a,x)=>a+x.qty*x.p.price,0);basketBar.classList.toggle('hidden',count===0);basketSummary.textContent=`${count} item${count===1?'':'s'}`;basketTotalSmall.textContent=money(total);basketTotal.textContent=money(total);basketItems.innerHTML=es.length?es.map(x=>`<div class="basket-item"><div><b>${esc(x.p.name)}</b><div class="sub">${money(x.p.price)} each · ${money(x.qty*x.p.price)}</div></div><div class="counter"><button data-dec="${x.p.id}">−</button><b>${x.qty}</b><button data-inc="${x.p.id}">+</button></div></div>`).join(''):'<div class="empty">Basket is empty.</div>';document.querySelectorAll('[data-dec]').forEach(b=>b.addEventListener('click',()=>changeBasket(b.dataset.dec,-1)));document.querySelectorAll('[data-inc]').forEach(b=>b.addEventListener('click',()=>changeBasket(b.dataset.inc,1)))}
    function changeBasket(id,d){const p=state.products.find(x=>x.id===id);const n=(state.basket[id]||0)+d;if(n<=0)delete state.basket[id];else state.basket[id]=Math.min(p.qty,n);saveBasketOnly()}
    function completeSale(){const es=basketEntries(); if(!es.length){toast('Basket is empty');return} if(es.some(x=>x.qty>x.p.qty)){toast('Not enough stock for one or more items');return} const items=es.map(x=>({productId:x.p.id,name:x.p.name,qty:x.qty,price:x.p.price,cost:x.p.cost||0}));const total=items.reduce((a,i)=>a+i.qty*i.price,0);const now=Date.now();items.forEach(i=>{const p=state.products.find(x=>x.id===i.productId);p.qty-=i.qty;state.movements.unshift({id:uid(),type:'sale',productId:p.id,name:p.name,qty:-i.qty,at:now})});state.sales.unshift({id:uid(),day:todayKey(),at:now,total,items});state.basket={};save();closeSheet('basketSheet');go('home');toast(`Sale completed · ${money(total)}`)}

    function renderProducts(){const q=productSearch.value.trim().toLowerCase();const ps=state.products.filter(p=>p.name.toLowerCase().includes(q));productList.innerHTML=ps.length?ps.map(p=>`<button class="row" data-edit="${p.id}" style="width:100%;color:inherit;text-align:left"><div class="meta"><div class="name">${p.emoji||'📦'} ${esc(p.name)}</div><div class="sub">${labelType(p.type)} · ${money(p.price)}${p.barcode?' · '+esc(p.barcode):''}</div></div><div class="qty ${p.qty<=p.low?'low':''}">${p.qty}</div></button>`).join(''):'<div class="empty">No products yet.</div>';document.querySelectorAll('[data-edit]').forEach(b=>b.addEventListener('click',()=>openProduct(b.dataset.edit)))}
    function labelType(t){return t==='prepared'?'Made here':t==='packaged'?'Packaged':'Loose'}
    function openProduct(id=''){const p=state.products.find(x=>x.id===id);productSheetTitle.textContent=p?'Edit product':'Add product';productId.value=p?.id||'';pName.value=p?.name||'';pType.value=p?.type||'loose';pCategory.value=p?.category||'';pPrice.value=p?.price??'';pCost.value=p?.cost??'';pQty.value=p?.qty??0;pLow.value=p?.low??5;pBarcode.value=p?.barcode||'';deleteProductBtn.style.display=p?'block':'none';openSheet('productSheet')}
    function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
    productForm.addEventListener('submit',e=>{e.preventDefault();const id=productId.value;const obj={id:id||uid(),name:pName.value.trim(),type:pType.value,category:pCategory.value.trim(),price:Number(pPrice.value),cost:Number(pCost.value)||0,qty:Math.max(0,parseInt(pQty.value||0)),low:Math.max(0,parseInt(pLow.value||0)),barcode:pBarcode.value.trim(),emoji:pickEmoji(pCategory.value,pType.value)};if(!obj.name||Number.isNaN(obj.price)){toast('Enter a product name and price');return}const dupe=state.products.find(p=>p.barcode&&obj.barcode&&p.barcode===obj.barcode&&p.id!==id);if(dupe){toast('That barcode is already linked to another product');return}if(id){state.products[state.products.findIndex(p=>p.id===id)]={...state.products.find(p=>p.id===id),...obj}}else state.products.push(obj);state.movements.unshift({id:uid(),type:id?'edit_product':'add_product',name:obj.name,qty:0,at:Date.now()});save();closeSheet('productSheet');toast(id?'Product updated':'Product added')});
    deleteProductBtn.addEventListener('click',()=>{const id=productId.value;const p=state.products.find(x=>x.id===id);if(!p)return;if(!confirm(`Delete ${p.name}?`))return;state.products=state.products.filter(x=>x.id!==id);delete state.basket[id];save();closeSheet('productSheet');toast('Product deleted')});
    function pickEmoji(cat,type){const c=cat.toLowerCase();if(type==='prepared')return'🥯';if(c.includes('drink'))return'🥤';if(c.includes('sweet'))return'🍬';if(c.includes('bread')||c.includes('grocery'))return'🍞';return'📦'}

    function renderStockInOptions(){siProduct.innerHTML=state.products.map(p=>`<option value="${p.id}">${esc(p.name)} · ${p.qty} in stock</option>`).join('');updateStockInHint()}
    function updateStockInHint(){const p=state.products.find(x=>x.id===siProduct.value);if(!p)return;siQtyLabel.textContent=p.type==='prepared'?'Quantity made / prepared':'Quantity received';stockInHint.textContent=p.type==='prepared'?'Use this for today’s fresh batch. The quantity will be added to available stock.':'Use this when new stock arrives from a supplier.'}
    stockInForm.addEventListener('submit',e=>{e.preventDefault();const p=state.products.find(x=>x.id===siProduct.value);const q=parseInt(siQty.value);if(!p||!q||q<1)return;p.qty+=q;state.movements.unshift({id:uid(),type:'stock_in',productId:p.id,name:p.name,qty:q,at:Date.now()});save();closeSheet('stockInSheet');toast(`${q} ${p.name} added`)});

    function renderCount(){countList.innerHTML=state.products.map(p=>`<div class="row"><div class="meta"><div class="name">${esc(p.name)}</div><div class="sub">Expected: ${p.qty}</div></div><input data-count="${p.id}" type="number" min="0" step="1" value="${p.qty}" style="width:86px;background:#1d1d1d;color:#fff;border:1px solid #2a2a2a;border-radius:12px;padding:10px;text-align:center" /></div>`).join('')}
    saveCountBtn.addEventListener('click',()=>{const now=Date.now();let diffs=0;document.querySelectorAll('[data-count]').forEach(inp=>{const p=state.products.find(x=>x.id===inp.dataset.count);const actual=Math.max(0,parseInt(inp.value||0));const diff=actual-p.qty;if(diff!==0)diffs++;state.counts.unshift({id:uid(),productId:p.id,name:p.name,expected:p.qty,actual,diff,at:now});if(diff!==0)state.movements.unshift({id:uid(),type:'count_adjustment',productId:p.id,name:p.name,qty:diff,at:now});p.qty=actual});save();go('home');toast(diffs?`Count saved · ${diffs} difference${diffs===1?'':'s'}`:'Count saved · no differences')});

    function renderHistory(){const sales=state.sales.map(s=>({at:s.at,html:`<div class="row"><div class="meta"><div class="name">Sale · ${s.items.reduce((a,i)=>a+i.qty,0)} items</div><div class="sub">${fmtTime(s.at)} · ${s.items.map(i=>`${i.qty}× ${esc(i.name)}`).join(', ')}</div></div><div class="qty">${money(s.total)}</div></div>`}));const moves=state.movements.filter(m=>m.type!=='sale').map(m=>({at:m.at,html:`<div class="row"><div class="meta"><div class="name">${moveLabel(m.type)} · ${esc(m.name)}</div><div class="sub">${fmtTime(m.at)}</div></div><div class="qty ${m.qty<0?'low':''}">${m.qty>0?'+':''}${m.qty||''}</div></div>`}));const all=[...sales,...moves].sort((a,b)=>b.at-a.at).slice(0,60);historyList.innerHTML=all.length?all.map(x=>x.html).join(''):'<div class="empty">No activity yet.</div>'}
    function moveLabel(t){return t==='stock_in'?'Stock in':t==='count_adjustment'?'Count adjustment':t==='add_product'?'Product added':t==='edit_product'?'Product edited':t}
    function fmtTime(ms){return new Intl.DateTimeFormat('en-ZA',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(ms))}

    async function startScanner(target='sale'){scanTarget=target;manualBarcode.value='';scanStatus.textContent='Starting camera…';openSheet('scanSheet');if(!navigator.mediaDevices?.getUserMedia){scanStatus.textContent='Camera scanning is not supported here. Type the barcode below.';return}try{scanStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}}});scanVideo.srcObject=scanStream;await scanVideo.play();if('BarcodeDetector' in window){const detector=new BarcodeDetector({formats:['ean_13','ean_8','upc_a','upc_e','code_128']});scanStatus.textContent='Point the camera at the barcode.';const loop=async()=>{if(!scanStream)return;try{const codes=await detector.detect(scanVideo);if(codes[0]?.rawValue){handleBarcode(codes[0].rawValue);return}}catch{}scanTimer=setTimeout(loop,350)};loop()}else scanStatus.textContent='Live barcode detection is not supported in this browser. Type the barcode below.'}catch{scanStatus.textContent='Camera permission was not available. Type the barcode below.'}}
    function stopScanner(){if(scanTimer)clearTimeout(scanTimer);scanTimer=null;if(scanStream){scanStream.getTracks().forEach(t=>t.stop());scanStream=null}scanVideo.srcObject=null}
    function handleBarcode(code){code=String(code||'').trim();if(!code)return;stopScanner();closeSheet('scanSheet');if(scanTarget==='product'){pBarcode.value=code;toast('Barcode captured');return}const p=state.products.find(x=>x.barcode===code);if(p){addToBasket(p.id,1);toast(`${p.name} scanned`)}else{openProduct();pBarcode.value=code;productSheetTitle.textContent='New barcode product';toast('Barcode not found · add product details')}}
    useBarcodeBtn.addEventListener('click',()=>handleBarcode(manualBarcode.value));scanBtn.addEventListener('click',()=>startScanner('sale'));scanIntoProductBtn.addEventListener('click',()=>startScanner('product'));

    function renderAll(){renderHome();renderSaleProducts();renderBasket();renderProducts();renderStockInOptions();renderCount();renderHistory()}
    function uid(){return 'id_'+Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
    saleSearch.addEventListener('input',renderSaleProducts);productSearch.addEventListener('input',renderProducts);document.querySelectorAll('.seg button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.seg button').forEach(x=>x.classList.remove('active'));b.classList.add('active');saleFilter=b.dataset.filter;renderSaleProducts()}));
    openBasketBtn.addEventListener('click',()=>openSheet('basketSheet'));reviewBasketBtn.addEventListener('click',()=>openSheet('basketSheet'));completeSaleBtn.addEventListener('click',completeSale);addProductBtn.addEventListener('click',()=>openProduct());openStockIn.addEventListener('click',()=>{renderStockInOptions();openSheet('stockInSheet')});siProduct.addEventListener('change',updateStockInHint);
    resetDemoBtn.addEventListener('click',()=>{if(confirm('Reset TuckStock to the original demo data?')){state=demoState();save();toast('Demo reset')}});
    if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}))}
    renderAll();
  